per_listener_settings true

# --- PORT 1883 (Zwykły - opcjonalnie) ---
listener 1883
allow_anonymous true

# --- PORT 8883 (Szyfrowany TLS - dla ROS 2) ---
listener 8883

# Ścieżki do certyfikatów serwera (które wygenerowałeś w Kroku 1)
certfile /home/rafal/Web_Speech_remote_control/sros2_ws/mqtt_certs/mqtt_broker.crt
keyfile /home/rafal/Web_Speech_remote_control/sros2_ws/mqtt_certs/mqtt_broker.key

# Ścieżka do CA (żeby broker mógł sprawdzić, czy klient ROS jest zaufany)
cafile /home/rafal/Web_Speech_remote_control/sros2_ws/mqtt_certs/ca_root.crt

# Bezpieczeństwo
allow_anonymous false   # Zabroń wchodzenia bez certyfikatu
require_certificate true # Wymuś pokazanie certyfikatu przez klienta (mTLS)
use_identity_as_username true # Użyj nazwy z certyfikatu (CN) jako nazwy użytkownika
